### ISSUE TITLE
[Feature] Add PR/Issue template

### ISSUE THREAD

**Issue by freddy5566** [NTUT-NPC/tat_gogogo#22]
## Summary
add pr/issue template for convenient

**Comment by thelebdev** [comment]
Is there a specific format or requirements?

**Comment by freddy5566** [comment]
nope, but our template should be as clear as possible

**Comment by thelebdev** [comment]
Do I need certain rights to push my branch?

**Comment by freddy5566** [comment]
Hi @christopheelkhoury,

there's no need to have right to open PR, but you gotta fork this project and clone the project that you just forked, and open branch before you commit, notice that the branch name in here I would suggest branch name to be `feature/github-template`, while you finish your changes then you could push branch to remote.
