### ISSUE TITLE
[Refactor] Wrong status code 

### ISSUE THREAD

**Issue by freddy5566** [NTUT-NPC/tat_gogogo#33]
**Is your feature request related to a problem? Please describe.**

the GET api shouldn't return 201 status code

**Describe the solution you'd like**

it should return 200

**Describe alternatives you've considered**
change the status code from 201 to 200

**Additional context**

**Comment by thelebdev** [comment]
@jamfly how can you reproduce the error?
for example: Run the server, send an HTTP Request to a specific URL with specific parameters, etc.

**Comment by freddy5566** [comment]
`/auth/curriculums/courses`, `/auth/curriculums/semesters` these two api, if you fit the correct parameters it will return `201`, it's a bug that I forget to change status code while I add JWT support.
